TIP:
  # ------ Load Cache and Features ------
  # load_cache: False
  # load_pre_feat: False

  load_cache: True
  load_pre_feat: True


  # ------ Hyperparamters ------
  search_hp: True
  # search_hp: False

  search_scale: [13, 13]
  search_step: [200, 20]

  init_beta: 1.0
  init_alpha: 2.0

  dataset_prompt_template: ['{} texture.']


  # ------ Basic Config ------
  dataset: 'dtd'
  shots: 16
  backbone: 'RN50'

  lr: 0.001
  augment_epoch: 10
  train_epoch: 20