TIP:
  # ------ Load Cache and Features ------
  # load_cache: False
  # load_pre_feat: False

  load_cache: True
  load_pre_feat: True


  # ------ Hyperparamters ------
  search_hp: True
  # search_hp: False

  search_scale: [7, 3]
  search_step: [200, 20]

  init_beta: 1.0
  init_alpha: 1.17

  dataset_prompt_template: ["itap of a {}.",
                        "a bad photo of the {}.",
                        "a origami {}.",
                        "a photo of the large {}.",
                        "a {} in a video game.",
                        "art of the {}.",
                        "a photo of the small {}."]


  # ------ Basic Config ------
  dataset: 'imagenet'
  shots: 16
  backbone: 'RN50'

  lr: 0.001
  augment_epoch: 10
  train_epoch: 20