TIP:
  # ------ Load Cache and Features ------
  # load_cache: False
  # load_pre_feat: False

  load_cache: True
  load_pre_feat: True


  # ------ Hyperparamters ------
  search_hp: True
  # search_hp: False

  search_scale: [50, 50]
  search_step: [200, 20]

  init_beta: 1.0
  init_alpha: 10.0

  dataset_prompt_template: ['a photo of a {}, a type of flower.']


  # ------ Basic Config ------
  dataset: 'oxford_flowers'
  shots: 16
  backbone: 'RN50'

  lr: 0.001
  augment_epoch: 10
  train_epoch: 20