DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 256
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]
  random_resized_crop_scale: (0.5, 1.0)

OPTIM:
  NAME: "adam" # "sgd_momentum"
  LR: 0.002
  MAX_EPOCH: 150 # 200 5000
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: -1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5
  MOMENTUM: 0.1
  SGD_DAMPNING: 0.1

TRAIN:
  PRINT_FREQ: 5

TEST:
  FINAL_MODEL: "best_val"
  EVALUATOR :  "Classification"  # "Classification"

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"